swagger:
  title: 博客系统接口文档
  description: 博客系统—问答管理接口
  exclude-path: /error # 剔除请求

server:
  port: 8002
  servlet:
    context-path: /question

spring:
  application:
    name: question-server # 应用名
  # 数据源配置
  datasource:
    username: root
    password: taoliankuan
    url: jdbc:mysql://127.0.0.1:3306/blog_question?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  cloud:
  nacos:
    discovery:
      server-addr:localhost:8848

mybatis-plus:
  type-aliases-package: com.tlk.blog.entities
  # xxxMapper.xml 路径
  mapper-locations: classpath*:com/tlk/blog/question/mapper/**/*.xml

# 日志级别，会打印sql语句
logging:
  level:
    com.tlk.blog.question.mapper: debug

